jobs:
  include:
    - language: erlang
      otp_release:
        - '22.0'
      before_script:
        - make -C yecc-leex clean
      script:
        - make -C yecc-leex all
        - make -C yecc-leex test
